services:
  # A Docker web service
  - type: web
    name: fastapi-example
    runtime: python3.8
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT